CREATE TABLE t_alere_alimentos (
                                   id bigint NOT NULL,
                                   is_actived boolean,
                                   created_timestamp timestamp without time zone,
                                   dt_fabricacao timestamp without time zone,
                                   dt_validade timestamp without time zone,
                                   ds_descricao text NOT NULL,
                                   ds_disponivel_ate timestamp without time zone,
                                   image text,
                                   nr_latitude double precision,
                                   nr_longitude double precision,
                                   is_perecivel boolean,
                                   is_reserved boolean,
                                   dt_reservado_ate timestamp without time zone,
                                   ds_tipo character varying(255),
                                   ds_titulo character varying(60) NOT NULL,
                                   updated_time_stamp timestamp without time zone,
                                   cadastrado_por bigint
);



ALTER TABLE t_alere_alimentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_alere_alimentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE t_alere_doacao (
                                id_doacao bigint NOT NULL,
                                created_timestamp timestamp without time zone,
                                is_realizado boolean,
                                updated_time_stamp timestamp without time zone,
                                doador_id bigint,
                                receptor_id bigint,
                                solicitacao_id bigint
);



ALTER TABLE t_alere_doacao ALTER COLUMN id_doacao ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_alere_doacao_id_doacao_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE t_alere_endereco (
                                  id_endereco bigint NOT NULL,
                                  ds_bairro character varying(40),
                                  ds_cep character varying(8),
                                  ds_cidade character varying(80),
                                  ds_complemento character varying(100),
                                  created_timestamp timestamp without time zone,
                                  ds_estado character varying(255),
                                  ds_logradouro character varying(100),
                                  ds_numero character varying(5),
                                  updated_time_stamp timestamp without time zone,
                                  user_id bigint
);


ALTER TABLE t_alere_endereco ALTER COLUMN id_endereco ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_alere_endereco_id_endereco_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE t_alere_roles (
                               id_role bigint NOT NULL,
                               created_timestamp timestamp without time zone,
                               ds_role character varying(40) NOT NULL,
                               is_deafult boolean,
                               updated_time_stamp timestamp without time zone
);


ALTER TABLE t_alere_roles ALTER COLUMN id_role ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_alere_roles_id_role_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE t_alere_solicitacao (
                                     id_solicitacao bigint NOT NULL,
                                     created_timestamp timestamp without time zone,
                                     ds_mensagem character varying(255),
                                     is_respondida boolean,
                                     ds_status character varying(255),
                                     updated_time_stamp timestamp without time zone,
                                     alimento_id bigint,
                                     solicitador_id bigint,
                                     doador_id bigint
);



ALTER TABLE t_alere_solicitacao ALTER COLUMN id_solicitacao ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_alere_solicitacao_id_solicitacao_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE t_alere_user (
                              id_user bigint NOT NULL,
                              is_actived boolean,
                              is_banned boolean,
                              is_confirmed boolean,
                              created_timestamp timestamp without time zone,
                              ds_email character varying(160) NOT NULL,
                              nm_user character varying(120) NOT NULL,
                              ds_password character varying(255) NOT NULL,
                              ds_telefone character varying(255) NOT NULL,
                              terms_and_condicions boolean,
                              updated_time_stamp timestamp without time zone
);



ALTER TABLE t_alere_user ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_alere_user_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE t_alere_user_roles (
                                    user_id bigint NOT NULL,
                                    role_id bigint NOT NULL
);



ALTER TABLE ONLY t_alere_alimentos
    ADD CONSTRAINT t_alere_alimentos_pkey PRIMARY KEY (id);



ALTER TABLE ONLY t_alere_doacao
    ADD CONSTRAINT t_alere_doacao_pkey PRIMARY KEY (id_doacao);



ALTER TABLE ONLY t_alere_endereco
    ADD CONSTRAINT t_alere_endereco_pkey PRIMARY KEY (id_endereco);


ALTER TABLE ONLY t_alere_roles
    ADD CONSTRAINT t_alere_roles_pkey PRIMARY KEY (id_role);



ALTER TABLE ONLY t_alere_solicitacao
    ADD CONSTRAINT t_alere_solicitacao_pkey PRIMARY KEY (id_solicitacao);



ALTER TABLE ONLY t_alere_user
    ADD CONSTRAINT t_alere_user_pkey PRIMARY KEY (id_user);



ALTER TABLE ONLY t_alere_roles
    ADD CONSTRAINT uk_2msoa5p5mbrq09whg4tboapuf UNIQUE (ds_role);



ALTER TABLE ONLY t_alere_user
    ADD CONSTRAINT uk_agxcmtb18stktf4u4ob094tgi UNIQUE (ds_email);


ALTER TABLE ONLY t_alere_doacao
    ADD CONSTRAINT fk2dn4e6kv0tybyighrfiu4x43n FOREIGN KEY (solicitacao_id) REFERENCES public.t_alere_solicitacao(id_solicitacao);



ALTER TABLE ONLY t_alere_doacao
    ADD CONSTRAINT fk6gjohqv2tn9ywjtrka6owt6q5 FOREIGN KEY (doador_id) REFERENCES public.t_alere_user(id_user);



ALTER TABLE ONLY t_alere_user_roles
    ADD CONSTRAINT fk6tneystq7pea93t6gbhy0xe83 FOREIGN KEY (role_id) REFERENCES public.t_alere_roles(id_role);


ALTER TABLE ONLY t_alere_alimentos
    ADD CONSTRAINT fkb8gs5guoe0b172ifm73tikdcr FOREIGN KEY (cadastrado_por) REFERENCES public.t_alere_user(id_user);



ALTER TABLE ONLY t_alere_solicitacao
    ADD CONSTRAINT fkccogj2gp7msujl9og0dnlykns FOREIGN KEY (doador_id) REFERENCES public.t_alere_user(id_user);



ALTER TABLE ONLY t_alere_doacao
    ADD CONSTRAINT fkcpgiv2ch1hvb2c1nuv3nl5yku FOREIGN KEY (receptor_id) REFERENCES public.t_alere_user(id_user);



ALTER TABLE ONLY t_alere_endereco
    ADD CONSTRAINT fkk1ed162gobkwstaf0fwh03a82 FOREIGN KEY (user_id) REFERENCES public.t_alere_user(id_user);



ALTER TABLE ONLY t_alere_solicitacao
    ADD CONSTRAINT fkly2bsls3lq90u2nia6l6vy7eh FOREIGN KEY (alimento_id) REFERENCES public.t_alere_alimentos(id);



ALTER TABLE ONLY t_alere_user_roles
    ADD CONSTRAINT fkmvrpqs7lgtc3e13decfcni291 FOREIGN KEY (user_id) REFERENCES public.t_alere_user(id_user);



ALTER TABLE ONLY t_alere_solicitacao
    ADD CONSTRAINT fks04ckge73mbyxssvcu2pgf3yn FOREIGN KEY (solicitador_id) REFERENCES public.t_alere_user(id_user);
